

"Name": "Copper Axe",
"Name": "Copper Fishing Rod",
"Name": "Copper Pickaxe",
"Name": "Copper Trap",
"Name": "Leather Pouch",
"Name": "Wool Basket",
"Name": "Iron Axe",
"Name": "Iron Fishing Rod",
"Name": "Iron Pickaxe",
"Name": "Iron Trap",
"Name": "Thick Leather Pouch",
"Name": "Silk Basket",
"Name": "Silver Axe",
"Name": "Silver Fishing Rod",
"Name": "Silver Pickaxe",
"Name": "Silver Trap",
"Name": "Sturdy Leather Pouch",
"Name": "Moonlit Basket",
"Name": "Gold Axe",
"Name": "Gold Fishing Rod",
"Name": "Gold Pickaxe",
"Name": "Gold Trap",
"Name": "Heavy Leather Pouch",
"Name": "Etheric Basket",
"Name": "Platinum Amulet",
"Name": "Platinum Axe",
"Name": "Platinum Fishing Rod",
"Name": "Platinum Pickaxe",
"Name": "Platinum Trap",
"Name": "Tough Leather Pouch",
"Name": "Shadow Basket",
"Name": "Platinum Ring",
"Name": "Mithril Axe",
"Name": "Mithril Fishing Rod",
"Name": "Mithril Pickaxe",
"Name": "Mithril Trap",
"Name": "Reinforced Leather Pouch",
"Name": "Celestial Basket",
"Name": "Adamantite Axe",
"Name": "Adamantite Fishing Rod",
"Name": "Adamantite Pickaxe",
"Name": "Adamantite Trap",
"Name": "Arcane Basket",
"Name": "Shadowhide Pouch",
"Name": "Eternium Axe",
"Name": "Eternium Fishing Rod",
"Name": "Eternium Pickaxe",
"Name": "Eternium Trap",
"Name": "Dragonhide Pouch",
"Name": "Aether Basket",
"Name": "Nyxium Axe",
"Name": "Nyxium Fishing Rod",
"Name": "Nyxium Pickaxe",
"Name": "Nyxium Trap",
"Name": "Nyxium Amulet",
"Name": "Abyssal Pouch",
"Name": "Astral Basket",
"Name": "Nyxium Ring",
"Name": "Cursed Amulet",
"Name": "Cursed Ring",
"Name": "Abyssal Amulet",
"Name": "Abyssal Ring",
"Name": "Corrupted Ring",
"Name": "Corrupted Amulet",
