
Tome
"Name": "Rarity Tome I",
"Name": "Rarity Tome II",
"Name": "Rarity Tome III"
"Name": "Rarity Tome I",
"Name": "Rarity Tome II",
"Name": "Rarity Tome III"
"Name": "Rarity Tome I",
"Name": "Rarity Tome II",
"Name": "Rarity Tome III"
"Name": "Rarity Tome I",
"Name": "Rarity Tome II",


Food
"Name": "Grilled Millow",
"Name": "Roasted Snapper",
"Name": "Spicy Barracuda",
"Name": "Frosted Sawfish Filet",
"Name": "Oasis Platter",
"Name": "Pet Exp Manual I",
"Name": "Shark Stew",
"Name": "Angler Soup",
"Name": "Abyss Feast",
"Name": "Pet Exp Manual II",
"Name": "Spiced Sea Wyrm",
"Name": "Stormray Fillet",
"Name": "Leviathan Roast",
"Name": "Marrow Roast",
"Name": "Pet Exp Manual III",
Wood - Charm
"Name": "Oak Plank",
"Name": "Oak Charm",
"Name": "Birch Plank",
"Name": "Birch Charm",
"Name": "Pine Plank",
"Name": "Pine Charm",
"Name": "Cedar Plank",
"Name": "Cedar Charm",
"Name": "Combat Exp Charm I",
"Name": "Ebony Plank",
"Name": "Ebony Charm",
"Name": "Ironwood Plank",
"Name": "Ironwood Charm",
"Name": "Combat Exp Charm II",
"Name": "Dragonwood Plank",
"Name": "Dragonwood Charm",
"Name": "Celestial Plank",
"Name": "Celestial Charm",
"Name": "Eldertree Plank",
"Name": "Eldertree Charm",
"Name": "Combat Exp Charm III",
Alchemy
"Name": "Whisperleaf Extract",
"Name": "Minor Attack Potion",
"Name": "Minor Defense Potion",
"Name": "Minor Speed Potion",
"Name": "Briarthorn Resine",
"Name": "Greater Attack Potion",
"Name": "Greater Defense Potion",
"Name": "Greater Speed Potion",
"Name": "Emberroot Essence",
"Name": "Mighty Attack Potion",
"Name": "Mighty Defense Potion",
"Name": "Mighty Speed Potion",
"Name": "Frostleaf Distillate",
"Name": "Resource Efficiency Potion",
"Name": "Superior Attack Potion",
"Name": "Superior Defense Potion",
"Name": "Superior Speed Potion",
"Name": "Task Efficiency Potion I",
"Name": "Dreanvine Sap",
"Name": "Grand Attack Potion",
"Name": "Grand Defense Potion",
"Name": "Grand Speed Potion",
"Name": "Spiritthorn Powder",
"Name": "Spirit Attack Potion",
"Name": "Spirit Defense Potion",
"Name": "Spirit Speed Potion",
"Name": "Shadowbloom Essence",
"Name": "Umbral Attack Potion",
"Name": "Umbral Defense Potion",
"Name": "Umbral Speed Potion",
"Name": "Defense Penetration Potion",
"Name": "Task Efficiency Potion II",
"Name": "Sunpetal Infusion",
"Name": "Radiant Attack Potion",
"Name": "Radiant Defense Potion",
"Name": "Radiant Speed Potion",
"Name": "Starlotus Extract",
"Name": "Celestial Attack Potion",
"Name": "Celestial Defense Potion",
"Name": "Celestial Speed Potion",
"Name": "Critical Hit Potion",
"Name": "Task Efficiency Potion III",
